language: c
env:
  # Nim versions to test against
  - CHOOSENIM_CHOOSE_VERSION=devel
  - CHOOSENIM_CHOOSE_VERSION=1.0.6
  - CHOOSENIM_CHOOSE_VERSION=0.20.2
  - CHOOSENIM_CHOOSE_VERSION=0.19.6
  - CHOOSENIM_CHOOSE_VERSION=0.18.0
  - CHOOSENIM_CHOOSE_VERSION=0.17.2
  - CHOOSENIM_CHOOSE_VERSION=0.16.0
  - CHOOSENIM_CHOOSE_VERSION=0.15.2

install:
  - curl https://nim-lang.org/choosenim/init.sh -sSf | sh -s -- -y
before_script:
  - set -e
  - export CHOOSENIM_NO_ANALYTICS=1
  - export PATH=~/.nimble/bin:$PATH
script:
  - nim --cc:$CC tests
branches:
  except:
    - gh-pages
